#ifndef INC_PORT_SETTINGS_H_
#define INC_PORT_SETTINGS_H_

#define NRF24_CE_PORT GPIOD
#define NRF24_CE_PIN GPIO_PIN_15

#define NRF24_CSN_PORT GPIOD
#define NRF24_CSN_PIN GPIO_PIN_14

#endif /* INC_PORT_SETTINGS_H_ */